[build]
  command = "flutter build web"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.19.6" 

[context.production.environment]
  FLUTTER_VERSION = "3.19.6"

[[plugins]]
  package = "netlify/plugin-install-flutter"
  inputs = { version = "3.19.6" } 
