// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBchY7DswRgtv07J5tX4NOmX5hzRMAZ0x8',
    appId: '1:625782292273:web:b1acaa64bfe90a45903a10',
    messagingSenderId: '625782292273',
    projectId: 'workerschedulerv0',
    authDomain: 'workerschedulerv0.firebaseapp.com',
    storageBucket: 'workerschedulerv0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABgjsg-M3g5EK9FboO9JVqHDRZJQOjRqQ',
    appId: '1:625782292273:android:095d9bf32223f6d4903a10',
    messagingSenderId: '625782292273',
    projectId: 'workerschedulerv0',
    storageBucket: 'workerschedulerv0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyju1CmyO6p1_hGUras4WJ0lS6jDjzKe8',
    appId: '1:625782292273:ios:b9024aaf84b0d60d903a10',
    messagingSenderId: '625782292273',
    projectId: 'workerschedulerv0',
    storageBucket: 'workerschedulerv0.appspot.com',
    iosBundleId: 'com.example.workSchedulerV0',
  );
}
